name: Setup Node

description: Setup Node.js with cache using a node version file

inputs:
  node-version-file:
    description: "Path to .nvmrc or node version file"
    required: false
    default: ".nvmrc"
  cache:
    description: "Dependency manager to cache (npm, yarn, pnpm)"
    required: false
    default: "npm"

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: ${{ inputs.cache }}
