name: Release Build

description: Releases the build to existing artifacts

inputs:
  upload_url:
    description: "URL for the release asset"
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Upload release asset
      uses: shogo82148/actions-upload-release-asset@v1.8.1
      with:
        upload_url: ${{ inputs.upload_url }}
        asset_path: release.tar.gz
        asset_content_type: application/gzip
