name: Set release tag

inputs:
  release_version:
    description: 'Release version number'
    required: true
    type: string

  branch_name:
    description: 'Name of the current branch'
    required: true
    type: string

  github_run_id:
    description: 'Name of the current branch'
    required: true
    type: string

outputs:
  release_version_tag:
    value: ${{ steps.set_tag.outputs.release_version_tag }}

runs:
  using: composite
  steps:
    - name: Set release tag
      id: set_tag
      shell: bash
      run: |
        VERSION="${{ inputs.release_version }}"
        BRANCH="${{ inputs.branch_name }}"

        echo "$VERSION"
        echo "$BRANCH"

        if [[ "$BRANCH" == "y25-099-2-migrate-actions" ]]; then
          TAG="${VERSION}-${{ inputs.github_run_id }}-develop"
        else
          TAG="$VERSION"
        fi

        echo "$TAG"


        echo "release_version_tag=$TAG" >> $GITHUB_OUTPUT
