name: Tag a docker image with the release version

inputs:
  image_name:
    description: 'Name of the docker image'
    required: true
    type: string

  branch_name:
    description: 'Name of the current branch'
    required: true
    type: string

  release_version_tag:
    description: 'The tag name for the image'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Tag image with release version
      shell: bash
      run: >-
        docker tag
        docker.pkg.github.com/${{ inputs.image_name }}:${{ inputs.branch_name }}
        docker.pkg.github.com/${{ inputs.image_name }}:${{ inputs.release_version_tag }}
