name: Generate an access token for a GitHub Application

inputs:
  app_id:
    description: 'ID for GitHub Application'
    required: true
    type: string

  private_key:
    description: 'Private key for GitHub Application'
    required: true
    type: string
  
outputs:
  github_token:
    value: ${{ steps.app-token.outputs.token }}

runs:
  using: composite
  steps:
    - name: Generate access token
      uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
    
    - name: Export token
      shell: bash
      run: echo "github_token=${{ steps.app-token.outputs.token }}" >> $GITHUB_OUTPUT
