name: Upload artifacts to Github Pages

runs:
  using: composite
  steps:
    - name: Upload artifact to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: doc # Path to the folder containing the Yard documentation (default is 'doc')
