name: Install Python dependencies

runs:
  using: composite
  steps:
    - name: Install Python dependencies
      run: |
        pip install mkdocs
        pip install mkdocs-material
        pip install mkdocs-glightbox
        pip install mkdocs-git-revision-date-localized-plugin
