name: Setup Environment

description: Checkout repo and setup environment

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: sanger/.github/.github/actions/checkout@y25-099-migrate-actions

    - name: Setup environment
      env:
        # note: job.services is **NOT** available inside composite actions
        # you must pass any needed env variables as inputs instead
        DBPORT: ${{ inputs.dbport }}
      run: |
        bundle config path vendor/bundle
        bin/setup

inputs:
  dbport:
    description: 'MySQL DB port'
    required: true
    default: '3306'
