name: Push a docker release to the registry
inputs:
  image_name:
    description: "Name of the docker image"
    required: true
    type: string

  release_version_tag:
    description: "The tag name for the image"
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Push tagged docker release
      shell: bash
      run: >-
        docker push docker.pkg.github.com/${{ inputs.image_name }}:${{ inputs.release_version_tag }}
