name: Build and tag a docker image

inputs:
  image_name:
    description: 'Name of the docker image'
    required: true
    type: string

  branch_name:
    description: 'Name of the current branch'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Build and tag the image for testing and release
      run: >-
        docker build .
        --file Dockerfile
        --tag docker.pkg.github.com/${image_name}:${branch_name}