# Reusable workflow to be called from other repos.
# Uses the third party 'add-to-project' action to add 'depfu' PRs
# to the Technical Debt project board.
# Requires a GitHub Personal Access Token to be passed in as a secret named 'token'.
# See LabWhere .github/workflows for an example of how to use this workflow.

name: Add dependencies to technical debt project

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  add-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/sanger/projects/12
          github-token: ${{ secrets.token }}
          labeled: depfu