name: Build and Append to Release

on:
  workflow_call:
    inputs:
      upload_url:
        required: true
        type: string

jobs:
  build-and-append-to-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Setup Environment
        run: |
          bundle config path vendor/bundle
          bin/setup

      - name: Compile Build
        run: ./compile-build

      - uses: shogo82148/actions-upload-release-asset@v1.3.1
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: release.tar.gz
          asset_content_type: application/gzip
