# Checks that the .release-version file has been updated
name: Check release version

on: workflow_call

jobs:
  check:
    runs-on: ubuntu-latest
    # only run when PR is not draft and when .release-version exists in the repository
    # This was added for this workflow to not to be executed when a PR is made to .github repository.
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Check if .release-version file has changed
      run: |
        git fetch origin ${{ github.base_ref }}
        if ! git diff --name-only origin/${{ github.base_ref }} ${{ github.head_ref }} | grep -q '^\.release-version$'; then
            echo "Please change the release version number"
            exit 1
        fi
