name: Checkout Repository

on:
  workflow_call: {}
  
jobs:
  setup:
    runs-on: ubuntu-latest  
    env:
      CHECKOUT_VERSION: ${{ vars.CHECKOUT_VERSION }}
    
    steps:
      uses: actions/checkout@v4
