name: Release Build

on:
  workflow_call:
    inputs:
      upload_url:
        description: 'URL for the release asset'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest  
    steps:
      - uses: sanger/.github/.github/workflows/checkout.yml@y25-099-migrate-actions

      # Adds the release to existing artifacts
      - uses: shogo82148/actions-upload-release-asset@v1.3.1
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: release.tar.gz
          asset_content_type: application/gzip
