name: Setup Environment

on:
  workflow_call: {}

jobs:
  setup:
    runs-on: ubuntu-latest  
      
    steps:
      - uses: sanger/.github/.github/workflows/checkout.yml@y25-099-migrate-actions

      - name: Setup environment
        env:
          DBPORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          bundle config path vendor/bundle
          bin/setup