name: Setup Ruby

on:
  workflow_call:
    inputs: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      CHECKOUT_VERSION: ${{ vars.CHECKOUT_VERSION }}

    steps:
      - uses: actions/checkout@${{ vars.CHECKOUT_VERSION }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically