name: Setup Ruby

on:
  workflow_call:
    inputs: {}

jobs:
  setup_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: sanger/.github/.github/actions/checkout@y25-099-migrate-actions
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true