name: Setup Ruby

on:
  workflow_call:
    inputs:
      node-version-file:
        description: 'Path to .nvmrc or node version file'
        required: false
        type: string
        default: '.nvmrc'

jobs:
  setup:
    runs-on: ubuntu-latest  }

    steps:
      - uses: sanger/.github/.github/workflows/checkout.yml@y25-099-migrate-actions

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node-version-file }}
          cache: "yarn"
