name: Setup Environment

on:
  workflow_call: {}

jobs:
  setup_env:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repo
        uses: sanger/.github/.github/actions/checkout@y25-099-migrate-actions
        
      - name: Setup environment
        env:
          DBPORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          bundle config path vendor/bundle
          bin/setup