name: Setup Environment

on:
  workflow_call: {}

jobs:
  checkout_repo:
    uses: sanger/.github/.github/workflows/checkout.yml@y25-099-migrate-actions

  setup_env:
    runs-on: ubuntu-latest  
    steps:
      - name: Setup environment
        env:
          DBPORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          bundle config path vendor/bundle
          bin/setup